blog/urls.py
from django.urls import path
from .views import HomeView, CategoryViewList, CategoryUpdateView, CategoryDeleteView, CategoryCreateView, PostCreateView, PostUpdateView, PostDeleteView, PostDeleteView, PostDetailView
from . import views
app_name = 'blog'

urlpatterns = [
    path('HomeView/', HomeView, name="home"),
    path('category/', CategoryViewList, name='category'),
    path('category/<int:pk>/update/', CategoryUpdateView, name='category-update'),
    path('category/<int:pk>/delete/', CategoryDeleteView, name='category-delete'),
    path('category/add/', CategoryCreateView, name='category-create'),
    path('post/add/', PostCreateView, name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView, name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView, name='post-delete'),
    # new url
    path('post/<int:pk>/', PostDetailView, name='post-detail'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.templatetags.static import static
from portfolio import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here the line with updated_by (number 8) can make more posts.
class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    created = models.DateTimeField(auto_now_add=True)
    created_by = models.IntegerField()
    updated_by = models.IntegerField(blank=True, null=True)


    def __str__(self):
        return self.name


    class Meta:
        verbose_name_plural = 'Categories'


class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='static/images')
    content = models.TextField()
    published = models.BooleanField(default=False)
    tags = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add=True)
    created_by = models.IntegerField()
    updated_by = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.title
        

blog/forms.py
from django import forms
from django.db.models import fields
from django.forms import widgets
from .models import Category, Post

class CategoryModelForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Category Name'})
        }


class PostModelForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'slug', 'category', 'image', 'content', 'published', 'tags']

blog/views.py
from django.core import paginator
from django.shortcuts import get_object_or_404, redirect, render
from blog.models import Category, Post
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from .forms import CategoryModelForm, PostModelForm
from django.contrib import messages

# Create your views here.
def HomeView(request):
    featuredPosts = Post.objects.order_by('-id')[:3]
    post_lists = Post.objects.order_by('-id')
    categories = Category.objects.order_by('-id')

    paginator = Paginator(post_lists, 5)
    page = request.GET.get('page')
    posts = paginator.get_page(page)

    context = {
        'featuredPosts' : featuredPosts,
        'posts': posts,
        'categories': categories
    }
    return render(request, 'blog/home.html', context)



@login_required
def PostCreateView(request):
    form = PostModelForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        obj.created_by = request.user.id
        obj.save()
        messages.success(request, 'Post created successfully')
        return redirect('blog:home')

    context = {
        'form': form,
        'valueBtn': 'Add',
        'title': 'Create Post'
    }

    return render(request, 'blog/post-form.html', context)


# New post detail view
def PostDetailView(request, pk):
    post = get_object_or_404(Post, pk=pk)
    context = {
        'post': post
    }
    return render(request, 'blog/post-detail.html', context)



@login_required
def PostUpdateView(request, pk):
    post_id = get_object_or_404(Post, pk=pk)
    form = PostModelForm(request.POST or None, request.FILES or None, instance=post_id)
    if form.is_valid():
        obj = form.save(commit=False)
        obj.updated_by = request.user.id
        obj.save()
        messages.success(request, 'Post updated successfully.')
        return redirect('blog:home')

    context = {
        'form': form,
        'valueBtn': 'Update',
        'title': 'Update Post'
    }

    return render(request, 'blog/post-form.html', context)


@login_required
def PostDeleteView(request, pk):
    query = get_object_or_404(Post, pk=pk)
    query.delete()
    messages.success(request, 'Post deleted successfully.')
    return redirect('blog:home')


    

@login_required
def CategoryViewList(request):
    cat = Category.objects.order_by('-id')
    paginator = Paginator(cat, 5)
    page = request.GET.get('page')
    categories = paginator.get_page(page)

    context = {
        'categories' : categories
    }

    return render(request, 'blog/category.html', context)


@login_required
def CategoryUpdateView(request, pk):
    cat_id = get_object_or_404(Category, pk=pk)
    form = CategoryModelForm(request.POST or None, instance=cat_id)
    if form.is_valid():
        obj = form.save(commit=False)
        obj.updated_by = request.user.id
        obj.save()
        messages.success(request, 'Category updated successfully.')
        return redirect('blog:category')


    context = {
        'form': form,
        'valueBtn': 'Update',
        'title': 'Update Category'
    }

    return render(request, 'blog/category-form.html', context)

        

@login_required
def CategoryDeleteView(request, pk):
    query = get_object_or_404(Category, pk=pk)
    query.delete()
    messages.success(request, 'Category deleted successfully')
    return redirect('blog:category')



@login_required
def CategoryCreateView(request):
    form = CategoryModelForm(request.POST or None)
    if form.is_valid():
        obj = form.save(commit=False)
        obj.created_by = request.user.id
        obj.save()
        messages.success(request, 'Category added successfully.')
        return redirect('blog:category')


    context = {
        'form': form,
        'valueBtn': 'Add',
        'title': 'Create Category'
    }

    return render(request, 'blog/category-form.html', context)

blog/templates/blog/category-form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<section class="s1">
<div class="main-container">
<h2 class="text-center">{{title}}</h2>
<hr>

<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{message.tags}}" {%endif%}>{{message}}</li>
    {% endfor %}
</ul>


    <div class="row">
        <div class="col-lg-9 col-md-8 col-sm 12 mx-auto">
            <form action="." method="POST">
                {% csrf_token %}
                <div class="form-group">{{form.name}}</div>
                <div class="form-group float-right">

                {% if valueBtn == 'Add' %}
                <button class="btn btn-success btn-sm" value='{{valueBtn}}'> <span class="fa 
                fa-plus"></span> Create </button>
                {% endif %}
                {% if valueBtn == 'Update' %}
                <button class="btn btn-success btn-sm" value='{{valueBtn}}'> <span class="fa 
                fa-edit"></span> Update </button>
                {% endif %}
            </div>
        </form>

        {% for field in form %}
        {% for error in field.errors %}
        <p class="text-danger">{{error|escape}}</p>
        {% endfor %}

        {% endfor %}


        </div>
    </div>
 </div>
    </section>
{% endblock content %}

blog/templates/blog/category.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}


<section class="s1">
<div class="main-container">
<ul class="messages">

    {% for message in messages %}
    <li {% if message.tags %} class="{{message.tags}}" {%endif%}>{{message}}</li>
    {% endfor %}
</ul>
<div class="row">

    <div class="col-10 mx-auto">
        <table class="table table-hover text-success">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Category Name</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
            
                {% for cat in categories %} 
                    <tr>
                        <th>{{forloop.counter}}</th>
                        <th>{{cat.name}}</th>
                        <th>
                            <a href="{% url 'blog:category-update' cat.pk %}" class="btn btn-outline-success btn-sm"> <span class="fa fa-edit"></span> </a>

                            <a href="{% url 'blog:category-delete' cat.pk %}" class="btn btn-outline-danger btn-sm"> <span class="fa fa-trash"></span> </a>
                            
                        </th>
                    </tr>

                {% endfor %}
            </tbody>
        </table>
        {% include 'blog/pagination.html' with obj_pagination=categories %}
    </div>
    
</div>
 </div>
    </section>


{% endblock content %}

blog/templates/blog/featuredPosts.html
<div class="container">
    <h4 class="text-muted mt-5">Featured Posts</h4>
    <hr />

    <div class="row gy-4">
        {% for post in featuredPosts %}
        <div class="col-lg-4 col-md-6 col-sm-6 col-12">
            <div class="card">
                <img src="{{post.image.url}}" class="card-img-top" />
                <div class="card-body">
                    <span class="tag">{{post.category|upper}}</span>
                    <h5 class="card-title"></h5>
                    <a href="">{{post.title}}</a>
                    <p class="card-text">{{post.content|truncatewords:10}}</p>
                    <p> <i class="fa fa-clock"></i> {{post.created|timesince}} ago</p>
{#                Added Link to post details page #}
                    <a href="{% url 'blog:post-detail' post.pk %}" class="btn btn-outline-dark">Read more...</a>

                    {% if user.is_authenticated %}
                    <a href="{% url 'blog:post-update' post.pk %}" class="btn btn-outline-success">
                        <span class="fa fa-pen"></span>
                    </a>
                    <a href="{% url 'blog:post-delete' post.pk %}" class="btn btn-outline-danger">
                        <span class="fa fa-trash"></span>
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

blog/templates/blog/home.html
{% extends 'base.html' %} {% block content %}
<section class="s1">
<div class="container">
    <div class="row gy-4">
    {% include './featuredPosts.html' with featuredPosts=featuredPosts %}
    </div>
    

    <div class="row">
        <div class="col-lg-9 col-12 mt-5">
            {% include './latestPosts.html' with post_lists=post_lists %}
        </div>
        <div class="col-lg-3 col-12 mt-5">
            {% include './sideBar.html' with categories=categories %} </div>
    </div>
</div>

</section>


{% endblock content %}

blog/templates/blog/latestPosts.html
<div class="container">
    <h4 class="text-muted mt-5">Latest posts</h4>
    <hr />

    {% for post in posts %}
    <div class="card mb-3">
        <div class="row gy-0">
            <div class="col-md-4">
                <img src="{{post.image.url}}" alt="" class="card-img" />
            </div>
        

            <div class="col-md-8">
                <div class="card-body">
                    <span class="tag">{{post.category|upper}}</span>
                    <h5 class="card-title">
                        <a href="" class="card-link-title"> {{post.title}} </a>
                    </h5>

                    <p class="card-text">{{post.content|truncatewords:20}}</p>
                    <a href="{% url 'blog:post-detail' post.pk %}" class="btn btn-outline-dark">Read more...</a>
           <!--- <a href="">read more ...</a> 
            <a href="" class="btn btn-secondary rounded-lg">Read more</a> -->
                    <p class="card-text text-muted">
                        <i class="fa fa-clock"></i>
                        {{post.created|timesince}} ago
                
                        {% if user.is_authenticated %}
                        <a href="{% url 'blog:post-update' post.pk %}" class="btn btn-outline-success">
                            <span class="fa fa-pen"></span>
                        </a>
                        <a href="{% url 'blog:post-delete' post.pk %}" class="btn btn-outline-danger">
                            <span class="fa fa-trash"></span>
                        </a>
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% include './pagination.html' with obj_pagination=posts %}

blog/templates/blog/pagination.html
<div class="row my-5">
    <div class="max-auto">
        <div class="Page navigation">
            <ul class="pagination">
                {% if obj_pagination.has_previous %}
                <li class="page-item">
                    <a href="?page=1" class="page-link">
                        <i class="fa fa-angle-double-left"></i>                      
                    </a>
                </li>
                <li class="page-item">
                    <a href="?page={{obj_pagination.previous_page_number}}"
                    class="page-link">
                <i class="fa fa-angle-left"></i>
                </a>
                </li>
                {% endif %}

                <li class="page-item">
                    <a href="" class="current page-link">
                        Page {{obj_pagination.number}} of
                        {{obj_pagination.paginator.num_pages}}
                    </a>
                </li>

                {% if obj_pagination.has_next %}
                <li class="page-item">
                    <a href="?page={{obj_pagination.next_page_number}}" class="page-link">
                        <i class="fa fa-angle-right"></i>
                    </a>
                </li>
                <li class="page-item">
                    <a href="?=page{{obj_pagination.paginator.num_pages}}" class="page-link">
                        <i class="fa fa-angle-double-right"></i>

                    </a>
                </li>

                {% endif %}


            </ul>
        </div>
    </div>
</div>

blog/templates/blog/post-detail.html
{% extends 'base.html' %}

{% block extra_css %}
    <style>
        .image {
            width: 800px;
            height: auto;

        }

        .content {
            display: flex;
            align-items: center;
        }

        .single-post-area .blog_details {
            padding-top: 26px;
        }

        .single-post-area .blog_details {
            box-shadow: none;
            padding: 0;

        }

        .meta {
            color: #999999;
            margin-bottom: 1em;
        }
    </style>
{% endblock %}

{% block content %}
<section class="s1">
<div class="main-container">
    <div class="container single-post-area mt-4">
        <div class="image">
            <img class="img-fluid" src="{{ post.image.url }}">
        </div>
        <div class="blog_details">
            <h2 class="mt-2 mb-2">{{ post.title }}</h2>
            <div class="meta">
                <span><i class="fa fa-list-alt me-2" aria-hidden="true"></i> {{ post.category }}</span> |
                <span><i class="fa fa-tag me-2 ms-2" aria-hidden="true"></i> {{ post.tags }}</span> |
                <span><i class="fa fa-calendar me-2 ms-2"></i> {{ post.created }}</span>
            </div>
            <div class="content">
                <p>{{ post.content | urlize }}</p>
            </div>
        </div>
    </div>
   </div>
    </section>
{% endblock %}

blog/templates/blog/post-form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<section class="s1">
<div class="main-container">
    <h2 class="text-center">{{title}}</h2> <hr>
    {% if messages %}
        <ul class="messages text-center">
            {% for message in messages %}
                <li {% if message.tags %} class="text-center" {% endif %}>{{message}}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <div class="row">
 
        <div class="col-lg-9 col-md-8 col-sm-12 mx-auto">
            <form action="." method="POST" enctype="multipart/form-data">
                {% csrf_token %} {{form.media}} <div class='form-group'>{{form|crispy}}</div>

                <div class="form-group float-right">

                    {% if valueBtn  == 'Add' %}
                        <button class="btn btn-success btn-sm" value='{{valueBtn}}'>
                            <span class="fa fa-plus"></span> Create 
                        </button>
                        <a href="/" class="btn btn-success btn-sm">
                            <span class="fa fa-arrow-left"></span>
                        </a>                  
                    {% endif %}

                    <!-- I am still a little doubtful about this following code because it implies that
                    people could manipulate my postings. We'll see later, though
                    Also, try to find more things to put. Not just Create and Update but some other features as well
                    Remember that to do this I also have to code on url and views-->
                    {% if valueBtn  == 'Update' %}
                    <button class="btn btn-success btn-sm" value='{{valueBtn}}'>
                        <span class="fa fa-edit"></span> Update 
                    </button>
                    <a href="/" class="btn btn-success btn-sm">
                        <span class="fa fa-arrow-left"></span>
                    </a>                  
                {% endif %}
                    
                </div>
            </form>

            {% for field in form %}

            {% for error in field.errors %}
            <p class="text-danger">{{error|escape}}</p>

            {% endfor %}

            {% endfor %}
            
        </div>
       
    </div>
 </div>
    </section>
{% endblock content %}

blog/templates/blog/sideBar.html
{% load static %}

<div>
    <br />
    <h5 class="text-muted mb-3 mt-4">Meet the Author</h5>
    <hr />
    <div class="card">
        <img src="{% static 'images/profile.png' %}" alt="" class="card-img-top" />
        <div class="card-body">
            <p class="card-text">
                By Software Engineer Francisco Guardado. Enjoy all the posts and make sure to follow me on Youtube
                 and Twitter.
                 I make posts about relaxing music, video games and more!
            </p>
            <a href="" class="btn btn-secondary rounded-lg">learn more</a>
        </div>
    </div>

        <div class="mt-5">
            <h5 class="text-muted">Social Media</h5>
            <p>
                <div class="btn-group">
                    <a href=""> <i class="fab fa-facebook"></i></a>
                    <a href="https://twitter.com/zurfaro"> <i class="fab fa-twitter"></i></a>
                    <a href="https://www.youtube.com/channel/UCjAsoGbAUBNiazl-dH-nc2w/videos"><i class="fab fa-youtube"></i></a>
                    <a href="https://www.youtube.com/channel/UCta0JKmzN_OyT1IX_Ouztqg/videos"> <i class="fab fa-youtube"></i></a>
                    <a href="https://www.amazon.com/dp/B083ZQVMT5?customId=B075382VY7&th=1"> <i class="fab fa-amazon"></i></a>
                </div>
            </p>
        </div>
        <div class="mt-5">
            <h5 class="text-muted">Categories</h5>
            <hr>
            <p>
                <ul class="list-group">
                    {% for category in categories %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        {{category.name|upper}}
                    </li>
                    {% endfor %}
                </ul>
            </p>
        </div>
    </div>