blog/urls.py
from django.urls import path
from .views import HomeView, CategoryViewList, CategoryUpdateView, CategoryDeleteView, CategoryCreateView, PostCreateView, PostUpdateView, PostDeleteView, PostDeleteView, PostDetailView
from . import views
app_name = 'blog'

urlpatterns = [
    path('HomeView/', HomeView, name="home"),
    path('category/', CategoryViewList, name='category'),
    path('category/<int:pk>/update/', CategoryUpdateView, name='category-update'),
    path('category/<int:pk>/delete/', CategoryDeleteView, name='category-delete'),
    path('category/add/', CategoryCreateView, name='category-create'),
    path('post/add/', PostCreateView, name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView, name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView, name='post-delete'),
    # new url
    path('post/<int:pk>/', PostDetailView, name='post-detail'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.templatetags.static import static
from portfolio import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-47692315-56"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-47692315-56');
	</script>
	<link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">
	<!-- This line is to give the font customized (we can google it to my own choice)-->


	<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&family=Russo+One&display=swap" rel="stylesheet">
	<!-- This line is to give the font customized (we can google it to my own choice) It also goes on the russo section for css-->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/default.css' %}" />
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />
    {% block extra_css %}{% endblock %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">
	<link id="theme-style" rel="stylesheet" type="text/css" href="">

<!-- for navbar)-->    
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
</head>
<body>
    {% include './navbar.html' %}
     {% block content %} 

     {% endblock %}


    {% include './footer.html' %}
    
</body>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
				<!-- Following code is for files to be linked up based on color. That way we don't need to type in the color name (leave it in blank) and website will change color by pressing the dots -->
	<script type="text/javascript">
		let static = "{% static 'css' %}"
	</script>
<script type="text/javascript" src="{% static 'js/script.js' %}"></script> 
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script> 
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

</html>

templates/footer.html
<section class="s1">
<div class="main-container">
<div class="container" style="margin-top:45px;">
    <div class="row my-5gy-4">
        <div class="col-lg-6 col-md-6 col-sm-6col-12">
            <h5 class="text-muted mb-3 fw-bold">About Us</h5>
          
            <h5 class="text-muted" style="margin-top:35px;">
                Amazing Entertainment, which you can see on youtube: Music and Gaming.
                </h5>
                <p>
                    All the music I make is by my own imagination.
                    The gaming I post on my Youtube channel is using Nintendo and PlayStation4/5.
                </p>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-12">
                    <h5 class="text-muted mb-3 fw-bold">Trending Slider</h5>
                    <hr /> 
                    
                    
                    <div style="margin-top:35px;" id="carouselExampleIndicators" class="carousel slide footer" data-bs-ride="carousel">
                        <ol class="carousel-indicators">
                          <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"></li>
                          <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"></li>
                          
                        </ol>
                        <div class="carousel-inner">
                          <div class="carousel-item active">
                           <!----> <img src="https://s3.amazonaws.com/prod-media.gameinformer.com/styles/full/s3/2020/09/10/f76c6ad3/orp_03_griffinbowarrow.jpg" class="d-block w-100" alt="https://www.youtube.com/watch?v=p1_wAjmNytc">
                          </div>
                          <div class="carousel-item">
                            <img src="https://assets1.ignimgs.com/2020/11/30/immortalsfenyxrising-blogroll-1606716025359.jpg?width=1280" class="d-block w-100" alt="...">
                          </div>
                          <div class="carousel-item">
                            <img src="https://i0.wp.com/caniplaythat.com/wp-content/uploads/2020/09/immortals-fenyx-rising.jpg?resize=800%2C445&ssl=1" class="d-block w-100" alt="...">
                          </div>
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-bs-slide="prev">
                          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                          <span class="visually-hidden">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-bs-slide="next">
                          <span class="carousel-control-next-icon" aria-hidden="true"></span>
                          <span class="visually-hidden">Next</span>
                        </a>
                      </div>       
        </div>
        <div class="model-footer float-right mt-5 text-center">
            Built & Designed by Francisco Guardado
        </div>
    </div>

</div>
     </div>
    </section>

templates/navbar.html
 {% load static %}
 <section class="s1">
  
		<div class="main-container">
			<div class="greeting-wrapper"> <!--Class called greeting wrapper #22 -->
				<h1>Francisco Guardado Blog</h1>
			</div>


			<div class="intro-wrapper">  <!--This is to get our items #24-->
				<div class="nav-wrapper">

					<!-- Link around dots-wrapper added after tutorial video -->
					<a href="{% url 'index' %}">
						<div class="dots-wrapper">
							<!-- This is so we change the browser dots of a macbook. They have same class but different id #30-->
							<div id="dot-1" class="browser-dot"></div>
							<div id="dot-2" class="browser-dot"></div>
							<div id="dot-3" class="browser-dot"></div>
						</div>
					</a>
					

					<ul id="navigation">  <!-- contact #35-->

<nav class="navbar navbar-expand-lg navbar-light ">
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
					 <li class="nav-item"><a class="nav-link" href="{% url 'index' %}">Home</a></li>
					   <li class="nav-item"><a class="nav-link" href="{% url 'feature' %}">Features</a></li>
					   <li class="nav-item"><a class="nav-link" href="{% url 'index' %}#contact">Contact</a></li>
						<li class="nav-item"><a class="nav-link" href="{% url 'register' %}">SignUp</a></li>
					   
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Blog
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
	  <a class="dropdown-item" href="{% url 'blog:home' %}">Blog</a>
             {% if user.is_authenticated %}

                
                    <a class="dropdown-item" href="{% url 'blog:category' %}" class="nav-link active">Category</a>
               
            
                    <a class="dropdown-item" href="{% url 'blog:category-create' %}" class="nav-link active">Add Category</a>
            
           
                    <a class="dropdown-item" href="{% url 'blog:post-create' %}" class="nav-link active">Add New Post</a>
              

                {% endif %} 

        </div>
      </li>
             {% if user.is_authenticated %}

                
                    <a href="" class="nav-link active">Welcome: {{user.username}}</a>
               
            
                   <a href="{% url 'logout' %}" class="nav-link active">Logout</a>
            
              {% else %}
                   <a href="{% url 'login' %}" class="nav-link active">Login</a>
              

                {% endif %} 

    </ul>
  </div>
</nav>









						

  
					</ul>
				</div>
<!--Following lines of code are for the main image and the dots to change color of the website.
tHE ZERO is so I don't put space on the words.
Remember to id everything (every element) so I can give color and other functions on css -->
				<div class="left-column">
					<img id="profile_pic" src="{% static 'images/Francisco.jpg' %}">
					<h5 style="text-align: center;line-height: 0;margin-top: 30px; margin-bottom: 30px;">Personalize Theme</h5>

					<div id="theme-options-wrapper">
						<div data-mode="light" id="light-mode" class="theme-dot" ></div>
						<div data-mode="blue" id="blue-mode" class="theme-dot"></div>
						<div data-mode="green" id="green-mode" class="theme-dot"></div>
						<div data-mode="purple" id="purple-mode" class="theme-dot"></div>
					</div>

					<p id="settings-note">*Theme settings will be saved for<br>your next vist</p>
				</div>

				<!-- The following lines are for the square of letters on the main page located to the right side of the website. In other words, positioning. This way I can understand positioning #38-->

<!--Next lines we wrap from div id="preview line to class="corner with divs : this is so we make a shadow (id= "preview shadow") -->
				<div class="right-column">

					<div id="preview-shadow"> <!--41 -->
						<div id="preview">
							<div id="corner-tl" class="corner"></div>
							<div id="corner-tr" class="corner"></div>
							<h3>What I Do</h3>
							<p>I was a lead developer in a past life, now I enjoy teaching courses.</p>
							<!-- the reason these divs are below is because the square on the right side of the website has a second square that is transparent. That second square is a little bit below the first one. And also it has two dots so those two dots are for these divs #39-->
							<div id="corner-br" class="corner"></div>
							<div id="corner-bl" class="corner"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section> 
    